apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dockerbox
spec:
  template:
    metadata:
      labels:
        app: dockerbox
    spec:
      dnsPolicy: Default
      volumes:
        - name: dockerbox
          emptyDir: {}
      containers:
        - name: dockerbox
          image: gliderlabs/dockerbox:latest
          securityContext:
            privileged: true
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
          ports:
            - name: http
              containerPort: 2375
          volumeMounts:
            - mountPath: /var/lib/docker
              name: dockerbox
---
kind: Service
apiVersion: v1
metadata:
  name: dockerbox
spec:
  clusterIP: None
  selector:
    app: dockerbox
  ports:
    - name: http
      targetPort: http
      port: 2375
